
import React from 'react';
import { motion } from 'framer-motion';
import { ScrollText, Award, AlertTriangle, Lightbulb, X, Calendar, Trash2, Download } from 'lucide-react';
import { CaseHistoryEntry } from '../types';

interface Props {
  history: CaseHistoryEntry[];
  onClose: () => void;
}

const HISTORY_KEY = 'medisim_er_v6_history';

const LearningLog: React.FC<Props> = ({ history, onClose }) => {
  const handleDelete = (id: string) => {
    try {
      const localHistory = localStorage.getItem(HISTORY_KEY);
      const entries = localHistory ? (JSON.parse(localHistory) as CaseHistoryEntry[]) : [];
      const updated = entries.filter(e => e.id !== id);
      localStorage.setItem(HISTORY_KEY, JSON.stringify(updated));
      // Refresh so the parent re-reads history from localStorage.
      window.location.reload();
    } catch (err) {
      console.error("Failed to delete entry:", err);
    }
  };

  const handleDownloadReport = (entry: CaseHistoryEntry) => {
    const content = `
CLINICAL PERFORMANCE REPORT
---------------------------
Diagnosis: ${entry.diagnosis}
Date: ${new Date(entry.timestamp).toLocaleString()}
Outcome: ${entry.outcome}
Score: ${entry.score}%

SUMMARY:
${entry.summary}

AREAS FOR IMPROVEMENT:
${entry.missedOpportunities.map(m => `- ${m}`).join('\n')}
${entry.criticalEvents.filter(e => e.type === 'negative').map(e => `- [${e.event}] ${e.feedback}`).join('\n')}

KEY LEARNING POINTS:
${entry.learningPoints.map(p => `- ${p}`).join('\n')}

Generated by MediSim ER
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MediSim_Report_${entry.diagnosis.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[100] bg-slate-950/95 backdrop-blur-xl flex items-center justify-center p-4 md:p-8"
    >
      <div className="max-w-5xl w-full h-full bg-slate-900 border border-slate-800 rounded-[2.5rem] flex flex-col overflow-hidden shadow-2xl">
        <header className="px-8 py-6 border-b border-slate-800 flex justify-between items-center">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-emerald-500/10 rounded-2xl flex items-center justify-center text-emerald-500">
              <ScrollText className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-2xl font-black text-white tracking-tight">Learning Log</h2>
              <p className="text-slate-500 text-xs uppercase tracking-widest font-bold">Clinical Performance History</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-3 rounded-2xl bg-slate-800 text-slate-400 hover:text-white transition-all"
          >
            <X className="w-6 h-6" />
          </button>
        </header>

        <div className="flex-1 overflow-y-auto p-8 custom-scrollbar">
          {history.length === 0 ? (
            <div className="h-full flex flex-col items-center justify-center text-center space-y-4">
              <div className="w-20 h-20 bg-slate-800 rounded-full flex items-center justify-center text-slate-600">
                <ScrollText className="w-10 h-10" />
              </div>
              <h3 className="text-xl font-bold text-slate-400">No cases recorded yet</h3>
              <p className="text-slate-500 max-w-xs">Complete your first simulation to start building your clinical learning record.</p>
            </div>
          ) : (
            <div className="grid gap-6">
              {history.map((entry) => (
                <motion.div 
                  key={entry.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="bg-slate-950/50 border border-slate-800 rounded-3xl p-6 hover:border-emerald-500/30 transition-all group"
                >
                  <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
                    <div className="flex items-center gap-4">
                      <div className="w-12 h-12 bg-slate-900 rounded-2xl flex items-center justify-center text-emerald-500 border border-slate-800">
                        <Award className="w-6 h-6" />
                      </div>
                      <div>
                        <h4 className="text-lg font-bold text-white">{entry.diagnosis}</h4>
                        <div className="flex items-center gap-3 text-[10px] font-bold text-slate-500 uppercase tracking-widest">
                          <span className="flex items-center gap-1">
                            <Calendar className="w-3 h-3" />
                            {new Date(entry.timestamp).toLocaleDateString()}
                          </span>
                          <span className="w-1 h-1 rounded-full bg-slate-700" />
                          <span className={entry.score >= 80 ? "text-emerald-500" : "text-yellow-500"}>
                            Score: {entry.score}%
                          </span>
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <button 
                        onClick={() => handleDownloadReport(entry)}
                        className="p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-slate-500 hover:text-emerald-400 hover:border-emerald-400/50 transition-all flex items-center gap-2"
                        title="Download Report (Local)"
                      >
                        <Download className="w-4 h-4" />
                        <span className="text-[10px] font-black uppercase tracking-widest hidden md:inline">Download</span>
                      </button>
                      <button
                        onClick={() => handleDelete(entry.id)}
                        className="p-2.5 rounded-xl bg-slate-900 border border-slate-800 text-slate-500 hover:text-red-400 hover:border-red-400/50 transition-all"
                        title="Delete Record"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </div>

                  <p className="text-slate-400 text-sm mb-6 leading-relaxed italic">
                    "{entry.summary}"
                  </p>

                  <div className="grid md:grid-cols-2 gap-6">
                    <div className="space-y-3">
                      <div className="flex items-center gap-2 text-red-400">
                        <AlertTriangle className="w-4 h-4" />
                        <span className="text-[10px] font-black uppercase tracking-widest">Areas for Improvement</span>
                      </div>
                      <ul className="space-y-2">
                        {entry.missedOpportunities.map((item, i) => (
                          <li key={i} className="text-xs text-slate-300 flex gap-2">
                            <span className="text-red-500 shrink-0">•</span>
                            {item}
                          </li>
                        ))}
                        {entry.criticalEvents.filter(e => e.type === 'negative').map((e, i) => (
                          <li key={`crit-${i}`} className="text-xs text-slate-300 flex gap-2">
                            <span className="text-red-500 shrink-0">•</span>
                            <span className="font-bold text-red-400/80">[{e.event}]</span> {e.feedback}
                          </li>
                        ))}
                      </ul>
                    </div>

                    <div className="space-y-3">
                      <div className="flex items-center gap-2 text-emerald-400">
                        <Lightbulb className="w-4 h-4" />
                        <span className="text-[10px] font-black uppercase tracking-widest">Key Learning Points</span>
                      </div>
                      <ul className="space-y-2">
                        {entry.learningPoints.map((point, i) => (
                          <li key={i} className="text-xs text-slate-300 flex gap-2">
                            <span className="text-emerald-500 shrink-0">✓</span>
                            {point}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          )}
        </div>
      </div>
    </motion.div>
  );
};

export default LearningLog;
